#!/usr/bin/env python3
import requests, json, mysql.connector
from datetime import datetime
from bs4 import BeautifulSoup

COLLECTION_LAG_DAYS = 0  # adjust if needed

def get_connection():
    return mysql.connector.connect(
        host="zburnside.mysql.pythonanywhere-services.com",
        user="zburnside",
        password="Bearsocks24!",
        database="zburnside$golfnow"
    )


def fetch_items():
    URL    = "https://app.ecwid.com/api/v3/19699130/products"
    PARAMS = {
      "category": 50930083,
      "responseFields": (
        "items(id,sku,inStock,name,price,priceInProductList,"
        "defaultDisplayedPrice,defaultDisplayedPriceFormatted,"
        "url,autogeneratedSlug,created,updated,warningLimit,"
        "categoryIds,volume,googleProductCategoryName,"
        "maxPurchaseQuantity,favorites,count,wholesalePrices)"
      ),
      "limit": 1000
    }
    HEADERS = {
      "Authorization": "Bearer secret_7xNQhjnK45XbeaaqzEWJG85BpyCTkTH3",
      "User-Agent": "Mozilla/5.0"
    }
    resp = requests.get(URL, headers=HEADERS, params=PARAMS, timeout=20)
    resp.raise_for_status()
    items = resp.json().get("items", [])

    today = datetime.utcnow().date()
    rows = []
    for it in items:
        rows.append({
            "collection_date": today,
            "id":                          it.get("id"),
            "sku":                         it.get("sku"),
            "inStock":                     int(it.get("inStock", 0)),
            "name":                        it.get("name"),
            "price":                       it.get("price"),
            "priceInProductList":          it.get("priceInProductList"),
            "defaultDisplayedPrice":       it.get("defaultDisplayedPrice"),
            "defaultDisplayedPriceFormatted": it.get("defaultDisplayedPriceFormatted"),
            "url":                         it.get("url"),
            "autogeneratedSlug":           it.get("autogeneratedSlug"),
            "created":                     it.get("created"),
            "updated":                     it.get("updated"),
            "warningLimit":                it.get("warningLimit"),
            "categoryIds":                 ",".join(map(str, it.get("categoryIds", []))),
            "volume":                      it.get("volume"),
            "googleProductCategoryName":   it.get("googleProductCategoryName"),
            "maxPurchaseQuantity":         it.get("maxPurchaseQuantity"),
            "favoritesCount":              int(it.get("favorites", {}).get("count", 0)),
            "wholesalePrices":             json.dumps(it.get("wholesalePrices", {})),
        })
    return rows


def main():
    rows = fetch_items()
    conn = get_connection()
    cur  = conn.cursor()
    # Add collection_date to schema and composite primary key
    cur.execute("""
      CREATE TABLE IF NOT EXISTS ecwid_products (
        collection_date DATE NOT NULL,
        id BIGINT NOT NULL,
        sku VARCHAR(255),
        inStock TINYINT(1),
        name VARCHAR(512),
        price DECIMAL(10,2),
        priceInProductList DECIMAL(10,2),
        defaultDisplayedPrice DECIMAL(10,2),
        defaultDisplayedPriceFormatted VARCHAR(50),
        url TEXT,
        autogeneratedSlug VARCHAR(255),
        created BIGINT,
        updated BIGINT,
        warningLimit INT,
        categoryIds TEXT,
        volume DECIMAL(10,2),
        googleProductCategoryName VARCHAR(255),
        maxPurchaseQuantity INT,
        favoritesCount INT,
        wholesalePrices JSON,
        PRIMARY KEY(collection_date, id)
      ) CHARACTER SET utf8mb4;
    """)

    insert_sql = """
      INSERT IGNORE INTO ecwid_products (
        collection_date, id, sku, inStock, name, price, priceInProductList,
        defaultDisplayedPrice, defaultDisplayedPriceFormatted,
        url, autogeneratedSlug, created, updated, warningLimit,
        categoryIds, volume, googleProductCategoryName,
        maxPurchaseQuantity, favoritesCount, wholesalePrices
      ) VALUES (
        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
      );
    """

    for r in rows:
        cur.execute(insert_sql, (
            r["collection_date"], r["id"], r["sku"], r["inStock"], r["name"],
            r["price"], r["priceInProductList"],
            r["defaultDisplayedPrice"], r["defaultDisplayedPriceFormatted"],
            r["url"], r["autogeneratedSlug"], r["created"],
            r["updated"], r["warningLimit"], r["categoryIds"],
            r["volume"], r["googleProductCategoryName"],
            r["maxPurchaseQuantity"], r["favoritesCount"],
            r["wholesalePrices"]
        ))

    conn.commit()
    cur.close()
    conn.close()
    print(f"✅ Inserted {len(rows)} rows for {rows[0]['collection_date']} ")

if __name__ == "__main__":
    main()
